version: '3'
services:
  nginx:
    image: nginx:1.15.7
    volumes:
      - .:/var/www/html/
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: docker/php
    volumes:
      - .:/var/www/html/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - db
      - elastic
      - rabbit

  php.consumer.skill_stats_recalculation:
    build: docker/php
    volumes:
      - .:/var/www/html/
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - db
      - elastic
      - rabbit
    command: php bin/console rabbitmq:consumer skill_stats_recalculation

  db:
    image: mariadb:10.4.0-bionic
    environment:
      MYSQL_DATABASE: db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql

  elastic:
    image: elasticsearch:6.5.3
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  rabbit:
    image: rabbitmq:3.7.8-management

  react:
    image: node:8.14.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["sleep", "365d"]

volumes:
  mysql-data:
  elastic-data: